# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>Link to Google</title>
    <style>
        body """
    yield """{
            font-family: Arial, sans-serif;
            text-align: center;
            margin-top: 50px;
        }
        a """
    yield """{
            display: inline-block;
            padding: 10px 20px;
            background-color: #4285f4;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            font-size: 18px;
        }
        a:hover """
    yield """{
            background-color: #3367d6;
        }
    </style>
</head>
<body>

    <h1>Welcome to the Link Page</h1>
    <a href=\"https://www.google.com\" target=\"_blank\">Go to Google</a>

</body>
</html>
"""
